# Generated by Django 5.2.17 on 2026-09-19 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_backfill_default_entities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('category', models.CharField(choices=[('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('building', 'Building'), ('furniture', 'Furniture'), ('it', 'IT'), ('other', 'Other')], max_length=20, verbose_name='category')),
                ('purchase_date', models.DateField(verbose_name='purchase date')),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='purchase cost')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='currency')),
                ('useful_life_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='useful life (months)')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='salvage value')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight line')], default='straight_line', max_length=20, verbose_name='depreciation method')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed'), ('under_maintenance', 'Under maintenance')], default='active', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organization.costcenter')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
