# Generated by Django 5.2.17 on 2026-09-19 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('organization', '0002_backfill_default_entities'),
        ('parties', '0001_initial'),
        ('tenants', '0007_tenantfeatures_assets_tenantfeatures_treasury'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodied_assets', to='parties.party'),
        ),
        migrations.AddField(
            model_name='asset',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organization.legalentity'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_asset_code_per_tenant'),
        ),
    ]
