# Generated by Django 5.2.17 on 2026-09-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_backfill_fixed_asset_accounts'),
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cost_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='cost (base currency)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='declining_balance_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='declining balance rate'),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.recurringentry'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposed_fraction',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='disposed fraction'),
        ),
        migrations.AddField(
            model_name='asset',
            name='in_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='in-service date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_depreciable',
            field=models.BooleanField(default=True, verbose_name='depreciable'),
        ),
        migrations.AddField(
            model_name='asset',
            name='opening_accumulated_depreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='opening accumulated depreciation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='purchase reference'),
        ),
        migrations.AddField(
            model_name='asset',
            name='salvage_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='salvage value (base currency)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(choices=[('straight_line', 'Straight line'), ('declining_balance', 'Declining balance')], default='straight_line', max_length=20, verbose_name='depreciation method'),
        ),
    ]
