# Generated by Django 5.2.17 on 2026-09-26 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_backfill_fixed_asset_accounts'),
        ('assets', '0003_asset_depreciation_fields'),
        ('tenants', '0013_tenantfeatures_cost_center_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAddition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount (base currency)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('extend_life_months', models.PositiveIntegerField(default=0, verbose_name='extend life (months)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additions', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.recurringentry')),
                ('old_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.recurringentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
