# Generated by Django 5.2.17 on 2026-09-26 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_backfill_fixed_asset_accounts'),
        ('assets', '0004_asset_addition'),
        ('parties', '0005_backfill_credit_limit_from_role_details'),
        ('tenants', '0013_tenantfeatures_cost_center_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('fraction', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='fraction')),
                ('proceeds_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='proceeds (base currency)')),
                ('proceeds_party_role', models.CharField(blank=True, max_length=20, verbose_name='proceeds party role')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('cost_share', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='cost share')),
                ('accum_share', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='accumulated depreciation share')),
                ('gain_loss', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='gain/loss')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved')], default='draft', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('proceeds_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('proceeds_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parties.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
