# Generated by Django 5.2.17 on 2026-09-26 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_disposal'),
        ('organization', '0005_legalentity_opening_approved_at'),
        ('tenants', '0013_tenantfeatures_cost_center_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.costcenter')),
                ('from_legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('to_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.costcenter')),
                ('to_legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.legalentity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
