# Generated by Django 5.2.17 on 2026-09-30 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_backfill_blank_account_type_and_normal_balance'),
        ('assets', '0006_asset_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdisposal',
            name='new_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.recurringentry'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='old_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.recurringentry'),
        ),
    ]
