# Generated by Django 5.2.17 on 2026-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_assetdisposal_new_entry_assetdisposal_old_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='reason'),
        ),
    ]
