# Generated by Django 5.2.17 on 2026-10-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0016_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='allow negative stock')),
                ('expiry_alert_days', models.PositiveIntegerField(default=30, verbose_name='expiry alert days')),
                ('freeze_warehouse_during_count', models.BooleanField(default=True, verbose_name='freeze warehouse during count')),
                ('default_tracking', models.CharField(choices=[('none', 'None'), ('serial', 'Serial'), ('batch', 'Batch')], default='none', max_length=10, verbose_name='default tracking')),
                ('show_weight_karat_fields', models.BooleanField(default=False, verbose_name='show weight/karat fields')),
                ('units_enabled', models.BooleanField(default=False, verbose_name='units of measure enabled')),
                ('barcode_enabled', models.BooleanField(default=False, verbose_name='barcode enabled')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'inventory settings',
                'verbose_name_plural': 'inventory settings',
            },
        ),
    ]
