# Generated by Django 5.2.17 on 2026-10-04 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_fiscalyear_deleted_at_fiscalyear_deleted_by'),
        ('inventory', '0002_unitofmeasure_itemuom_itemcategory_itembarcode_and_more'),
        ('organization', '0006_costcenter_deleted_at_costcenter_deleted_by_and_more'),
        ('sales', '0026_product_base_uom_product_category_and_more'),
        ('tenants', '0016_row_level_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_default', models.BooleanField(default=False, verbose_name='default warehouse')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjustment_account_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('cogs_account_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.costcenter')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventory_account_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='organization.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantity on hand')),
                ('qty_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantity reserved')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='sales.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantity on hand')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total value')),
                ('avg_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='average cost')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_costs', to='organization.legalentity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='sales.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'company_entity'), name='unique_item_cost_per_item_company')],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_warehouse_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('legal_entity',), name='unique_default_warehouse_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('item', 'warehouse'), name='unique_stock_level_per_item_warehouse'),
        ),
    ]
