# Generated by Django 5.2.17 on 2026-10-05 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_warehouse_stocklevel_itemcost_and_more'),
        ('sales', '0026_product_base_uom_product_category_and_more'),
        ('tenants', '0016_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, verbose_name='batch number')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='expiry')),
                ('manufactured', models.DateField(blank=True, null=True, verbose_name='manufactured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='sales.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BatchStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantity')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='inventory.batch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_stock', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=100, verbose_name='serial number')),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('issued', 'Issued'), ('in_transit', 'In transit'), ('disposed', 'Disposed')], default='in_stock', max_length=10, verbose_name='status')),
                ('received_doc', models.UUIDField(blank=True, null=True, verbose_name='received by document')),
                ('issued_doc', models.UUIDField(blank=True, null=True, verbose_name='issued by document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.batch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='sales.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.warehouse')),
            ],
            options={
                'verbose_name_plural': 'serial numbers',
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('tenant', 'item', 'number'), name='unique_batch_number_per_item'),
        ),
        migrations.AddConstraint(
            model_name='batchstock',
            constraint=models.UniqueConstraint(fields=('batch', 'warehouse'), name='unique_batch_stock_per_batch_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='serialnumber',
            constraint=models.UniqueConstraint(fields=('tenant', 'item', 'serial'), name='unique_serial_per_tenant_item'),
        ),
    ]
