# Generated by Django 5.2.17 on 2026-10-05 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_fiscalyear_deleted_at_fiscalyear_deleted_by'),
        ('inventory', '0004_batch_batchstock_serialnumber_and_more'),
        ('organization', '0006_costcenter_deleted_at_costcenter_deleted_by_and_more'),
        ('parties', '0006_party_deleted_at_party_deleted_by'),
        ('sales', '0026_product_base_uom_product_category_and_more'),
        ('tenants', '0016_row_level_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('count', 'Count'), ('opening', 'Opening')], max_length=10, verbose_name='kind')),
                ('number', models.CharField(blank=True, default='', max_length=32, verbose_name='number')),
                ('date', models.DateField(verbose_name='date')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='reference')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_documents', to='organization.legalentity')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_documents', to='parties.party')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='inventory.stockdocument')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_stock_documents', to='inventory.warehouse')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_documents', to='inventory.warehouse')),
            ],
            options={
                'verbose_name_plural': 'stock documents',
            },
        ),
        migrations.CreateModel(
            name='StockDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantity')),
                ('qty_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantity (base unit)')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='unit cost')),
                ('expected_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='expected quantity')),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='counted quantity')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='inventory.batch')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.costcenter')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockdocument')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_document_lines', to='sales.product')),
                ('serials', models.ManyToManyField(blank=True, related_name='document_lines', to='inventory.serialnumber')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.unitofmeasure')),
            ],
        ),
    ]
