# Generated by Django 5.2.17 on 2026-09-22 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_backfill_journal_entry_status_and_source'),
        ('organization', '0003_legalentity_tax_period_type'),
        ('tenants', '0009_tenant_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='rate (%)')),
                ('kind', models.CharField(choices=[('standard', 'Standard'), ('zero_rated', 'Zero rated'), ('exempt', 'Exempt'), ('out_of_scope', 'Out of scope'), ('reverse_charge', 'Reverse charge')], max_length=20, verbose_name='kind')),
                ('direction', models.CharField(choices=[('output', 'Output'), ('input', 'Input'), ('both', 'Both')], max_length=10, verbose_name='direction')),
                ('deductible', models.CharField(choices=[('full', 'Full'), ('none', 'None')], default='full', max_length=10, verbose_name='deductible')),
                ('country_code', models.CharField(default='SA', max_length=2, verbose_name='country code')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='effective from')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tax_code_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=10, verbose_name='period type')),
                ('start', models.DateField(verbose_name='start')),
                ('end', models.DateField(verbose_name='end')),
                ('status', models.CharField(choices=[('open', 'Open'), ('filed', 'Filed'), ('paid', 'Paid')], default='open', max_length=10, verbose_name='status')),
                ('filed_at', models.DateTimeField(blank=True, null=True, verbose_name='filed at')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_periods', to='organization.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-start'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'legal_entity', 'start', 'end'), name='unique_tax_period_range')],
            },
        ),
    ]
