# Generated by Django 5.2.17 on 2026-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_seed_tax_codes_and_periods_for_existing_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='currency',
            field=models.CharField(default='', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18, verbose_name='exchange rate'),
        ),
    ]
