# Generated by Django 5.2.17 on 2026-09-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_backfill_fx_realized_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_manual_posting',
            field=models.BooleanField(default=True, verbose_name='allow manual posting'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_control_override',
            field=models.BooleanField(default=False, verbose_name='control override'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reversed at'),
        ),
    ]
