# Generated by Django 5.2.17 on 2026-09-23 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_posted_entry_protection_triggers'),
        ('organization', '0004_legalentity_building_number_legalentity_city_and_more'),
        ('parties', '0003_backfill_party_iban_from_role_details'),
        ('treasury', '0006_statement_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_statement_line', None), _negated=True), fields=('bank_statement_line',), name='unique_journal_line_per_bank_statement_line'),
        ),
    ]
