# Generated by Django 5.2.17 on 2026-09-24 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_backfill_fiscal_years'),
        ('organization', '0005_legalentity_opening_approved_at'),
        ('parties', '0003_backfill_party_iban_from_role_details'),
        ('tenants', '0012_tenant_opening_balances_approved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_opening',
            field=models.BooleanField(default=False, verbose_name='opening entry'),
        ),
        migrations.CreateModel(
            name='OpeningBalanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('initial', 'Initial'), ('adjustment', 'Adjustment')], max_length=10, verbose_name='kind')),
                ('opening_date', models.DateField(verbose_name='opening date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='status')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('attestation_text', models.TextField(blank=True, verbose_name='attestation')),
                ('readiness_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_entry', to='accounting.journalentry')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_entries', to='organization.legalentity')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'opening balance entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_role', models.CharField(blank=True, max_length=20, verbose_name='party role')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='currency')),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1, max_digits=18, verbose_name='exchange rate')),
                ('debit_fc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_fc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('debit_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('open_items', models.JSONField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_lines', to='accounting.account')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_lines', to='organization.costcenter')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.openingbalanceentry')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_lines', to='parties.party')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
