# Generated by Django 5.2.17 on 2026-09-24 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_journalentry_is_opening_openingbalanceentry_and_more'),
        ('organization', '0005_legalentity_opening_approved_at'),
        ('tenants', '0012_tenant_opening_balances_approved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, default='', max_length=32, verbose_name='number')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('kind', models.CharField(choices=[('prepaid_expense', 'Prepaid expense'), ('deferred_revenue', 'Deferred revenue'), ('accrual', 'Accrual'), ('other', 'Other'), ('depreciation', 'Depreciation')], max_length=20, verbose_name='kind')),
                ('total_amount_base', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total amount')),
                ('installments_count', models.PositiveIntegerField(verbose_name='installments')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_entries', to='organization.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('first_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_entries_starting_here', to='accounting.fiscalperiod')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_entries_from', to='accounting.account')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_entries', to='organization.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_entries_to', to='accounting.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('due', 'Due'), ('generated', 'Generated'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='due', max_length=20, verbose_name='status')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('skip_reason', models.CharField(blank=True, max_length=255, verbose_name='skip reason')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='accounting.recurringentry')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_installment', to='accounting.journalentry')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_installments', to='accounting.fiscalperiod')),
            ],
            options={
                'ordering': ['entry', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'seq'), name='unique_recurring_installment_seq_per_entry')],
            },
        ),
    ]
