# Generated by Django 5.2.17 on 2026-09-30 20:53
# Sprint 6.6.3 (item 2): hand-edited from makemigrations' own output —
# AddIndex -> AddIndexConcurrently (django.contrib.postgres.operations)
# + atomic = False, so applying these never holds a long lock on a live
# table ("هجرة بلا قفل طويل" — CREATE INDEX CONCURRENTLY cannot run
# inside a transaction at all, hence atomic = False on the whole
# migration, not just these operations).

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('accounting', '0033_arabic_name_for_currency_rounding_account'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0005_legalentity_opening_approved_at'),
        ('parties', '0005_backfill_credit_limit_from_role_details'),
        ('tenants', '0015_tenant_require_2fa_for_roles'),
        ('treasury', '0008_move_untouched_treasury_to_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'legal_entity', 'date'], name='accounting_je_entity_date_idx'),
        ),
        AddIndexConcurrently(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'status'], name='accounting_je_status_idx'),
        ),
        AddIndexConcurrently(
            model_name='journalline',
            index=models.Index(fields=['account', 'entry'], name='jrnl_line_acct_entry_idx'),
        ),
        AddIndexConcurrently(
            model_name='openingbalanceentry',
            index=models.Index(fields=['tenant', 'status'], name='accounting_obe_status_idx'),
        ),
        AddIndexConcurrently(
            model_name='recurringentry',
            index=models.Index(fields=['tenant', 'status'], name='accounting_re_status_idx'),
        ),
    ]
