# Generated by Django 5.2.17 on 2026-09-19 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_journalentry_legal_entity_not_null'),
        ('organization', '0002_backfill_default_entities'),
        ('tenants', '0007_tenantfeatures_assets_tenantfeatures_treasury'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='name (English)')),
                ('party_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='organization', max_length=20, verbose_name='party type')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='tax number')),
                ('national_id_or_cr', models.CharField(blank=True, max_length=50, verbose_name='national ID / commercial registration')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.JSONField(blank=True, default=dict, verbose_name='address')),
                ('country_code', models.CharField(default='SA', max_length=2, verbose_name='country code')),
                ('default_currency', models.CharField(default='SAR', max_length=3, verbose_name='currency')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('employee', 'Employee'), ('affiliate', 'Affiliate company'), ('bank', 'Bank')], max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='role details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_roles', to='organization.legalentity')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='parties.party')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_party_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='partyrole',
            constraint=models.UniqueConstraint(fields=('party', 'role'), name='unique_role_per_party'),
        ),
    ]
