# Generated by Django 5.2.17 on 2026-09-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_backfill_party_iban_from_role_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='building number'),
        ),
        migrations.AddField(
            model_name='party',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='party',
            name='district',
            field=models.CharField(blank=True, max_length=255, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='party',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='party',
            name='short_address',
            field=models.CharField(blank=True, max_length=10, verbose_name='short address'),
        ),
        migrations.AddField(
            model_name='party',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='partyrole',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='credit limit'),
        ),
    ]
