# Generated by Django 5.2.17 on 2026-09-18 22:59

import apps.platform.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('platform', 'Platform'), ('tenant_user', 'Tenant user')], max_length=20)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('max_users', models.PositiveIntegerField(blank=True, null=True, verbose_name='max users')),
                ('max_branches', models.PositiveIntegerField(blank=True, null=True, verbose_name='max branches')),
                ('max_invoices_per_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='max invoices per month')),
                ('storage_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='storage (MB)')),
                ('feature_organization', models.BooleanField(default=False, verbose_name='organization structure')),
                ('feature_cost_centers', models.BooleanField(default=False, verbose_name='cost centers')),
                ('feature_inventory', models.BooleanField(default=False, verbose_name='inventory')),
                ('feature_purchasing', models.BooleanField(default=False, verbose_name='purchasing')),
                ('feature_hr', models.BooleanField(default=False, verbose_name='HR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('support', 'Support'), ('billing', 'Billing')], default='support', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('totp_secret', models.CharField(blank=True, max_length=64)),
                ('totp_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'platform user',
                'verbose_name_plural': 'platform users',
            },
            managers=[
                ('objects', apps.platform.managers.PlatformUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PlatformBackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='platform.platformuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'code_hash'), name='unique_backup_code_per_user')],
            },
        ),
    ]
