# Generated by Django 5.2.17 on 2026-09-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_restrict_auditlog_db_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='feature_assets',
            field=models.BooleanField(default=False, verbose_name='fixed assets'),
        ),
        migrations.AddField(
            model_name='plan',
            name='feature_treasury',
            field=models.BooleanField(default=False, verbose_name='treasury'),
        ),
    ]
