# Generated by Django 5.2.17 on 2026-09-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0005_seed_sprint3_plan_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_file_mb',
            field=models.PositiveIntegerField(default=20, verbose_name='max file size (MB)'),
        ),
    ]
