# Generated by Django 5.2.17 on 2026-10-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0006_plan_max_file_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_warehouses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='max warehouses'),
        ),
    ]
