# Generated by Django 5.2.17 on 2026-09-19 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_journalentry_legal_entity_not_null'),
        ('organization', '0002_backfill_default_entities'),
        ('parties', '0001_initial'),
        ('tenants', '0007_tenantfeatures_assets_tenantfeatures_treasury'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='bank name')),
                ('account_number', models.CharField(blank=True, max_length=64, verbose_name='account number')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, max_length=11, verbose_name='SWIFT')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='accounting.account')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banks', to='organization.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_boxes', to='parties.party')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_boxes', to='accounting.account')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_boxes', to='organization.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'cash boxes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Custody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodies', to='parties.party')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodies', to='accounting.account')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodies', to='organization.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'custodies',
                'ordering': ['name'],
            },
        ),
    ]
