# Generated by Django 5.2.17 on 2026-09-22 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_backfill_treasury_assets_features'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3, verbose_name='from currency')),
                ('to_currency', models.CharField(max_length=3, verbose_name='to currency')),
                ('date', models.DateField(verbose_name='date')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='rate')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], default='manual', max_length=10, verbose_name='source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'from_currency', 'to_currency', 'date'), name='unique_exchange_rate_per_pair_and_date')],
            },
        ),
    ]
