# Generated by Django 5.2.17 on 2026-09-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_bankstatement_bankstatementline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='max_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='max cash balance'),
        ),
        migrations.AddField(
            model_name='custody',
            name='limit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='custody limit'),
        ),
    ]
