# Generated by Django 5.2.17 on 2026-09-23 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_storage_used_bytes'),
        ('treasury', '0006_statement_import'),
        ('vouchers', '0002_source_statement_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='number')),
                ('count_date', models.DateField(verbose_name='count date')),
                ('denominations', models.JSONField(blank=True, default=dict, verbose_name='denominations')),
                ('counted_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='counted amount')),
                ('book_balance_snapshot', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='book balance snapshot')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='difference')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='treasury.cashbox')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('variance_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['-count_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('tenant', 'number'), name='unique_cash_count_number_per_tenant')],
            },
        ),
    ]
