# Generated by Django 5.2.17 on 2026-09-22 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_backfill_default_entities'),
        ('tenants', '0008_backfill_treasury_assets_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberingSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=30, verbose_name='document type')),
                ('prefix', models.CharField(max_length=10, verbose_name='prefix')),
                ('reset_yearly', models.BooleanField(default=True, verbose_name='reset numbering every year')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'doc_type'), name='unique_numbering_setting_per_doc_type')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'doc_type', 'legal_entity', 'year'), name='unique_document_sequence_scope', nulls_distinct=False)],
            },
        ),
    ]
