# Generated by Django 5.2.17 on 2026-09-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbering', '0002_backfill_existing_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnumberingsetting',
            name='include_entity_code',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='include entity code in the number'),
        ),
    ]
