# Generated by Django 5.2.17 on 2026-09-23 08:47

import apps.attachments.models
import apps.attachments.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0010_tenant_storage_used_bytes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('file', models.FileField(storage=apps.attachments.storage.AttachmentStorage(), upload_to=apps.attachments.models.attachment_upload_path, verbose_name='file')),
                ('original_name', models.CharField(max_length=255, verbose_name='original file name')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME type')),
                ('size', models.BigIntegerField(verbose_name='size (bytes)')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('category', models.CharField(choices=[('fatura_original', 'Original supplier invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('bank_letter', 'Bank letter'), ('id_document', 'ID document'), ('approval_minutes', 'Approval minutes'), ('other', 'Other')], max_length=20, verbose_name='category')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('upload_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='upload IP')),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], default='active', max_length=10, verbose_name='status')),
                ('void_reason', models.CharField(blank=True, max_length=255, verbose_name='void reason')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='voided at')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error'), ('skipped', 'Skipped (scanning disabled)')], default='pending', max_length=10, verbose_name='scan status')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='scanned at')),
                ('integrity_status', models.CharField(choices=[('unchecked', 'Unchecked'), ('ok', 'OK'), ('mismatch', 'Mismatch')], default='unchecked', max_length=10, verbose_name='integrity status')),
                ('integrity_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='integrity checked at')),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='extracted amount')),
                ('extracted_date', models.DateField(blank=True, null=True, verbose_name='extracted date')),
                ('extracted_ref', models.CharField(blank=True, max_length=100, verbose_name='extracted reference')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='attachments.attachment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['tenant', 'content_type', 'object_id'], name='attachments_tenant__d3e006_idx')],
            },
        ),
    ]
