# Generated by Django 5.2.17 on 2026-09-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='category',
            field=models.CharField(choices=[('fatura_original', 'Original supplier invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('bank_letter', 'Bank letter'), ('id_document', 'ID document'), ('approval_minutes', 'Approval minutes'), ('bank_statement', 'Bank statement'), ('other', 'Other')], max_length=20, verbose_name='category'),
        ),
    ]
