# Generated by Django 5.2.17 on 2026-09-24 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_attachment_category'),
        ('tenants', '0012_tenant_opening_balances_approved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('journal_entry', 'Journal Entry'), ('voucher_payment', 'Payment Voucher'), ('voucher_receipt', 'Receipt Voucher'), ('voucher_settlement', 'Settlement Voucher'), ('opening_balance', 'Opening Balance')], max_length=30, verbose_name='document type')),
                ('min_amount_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='minimum amount')),
                ('required_category', models.CharField(choices=[('fatura_original', 'Original supplier invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('bank_letter', 'Bank letter'), ('id_document', 'ID document'), ('approval_minutes', 'Approval minutes'), ('bank_statement', 'Bank statement'), ('other', 'Other')], max_length=30, verbose_name='required category')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['doc_type', '-min_amount_base'],
            },
        ),
    ]
