# Generated by Django 5.2.17 on 2026-10-03 11:05

import apps.attachments.models
import apps.attachments.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_attachmentrule_deleted_at_attachmentrule_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=apps.attachments.storage.attachment_storage, upload_to=apps.attachments.models.attachment_upload_path, verbose_name='file'),
        ),
    ]
