# Generated by Django 5.2.17 on 2026-09-22 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0009_seed_approvals_permissions'),
        ('tenants', '0009_tenant_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('journal_entry', 'Journal Entry'), ('invoice', 'Invoice')], max_length=30, verbose_name='document type')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='minimum amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules', to='access.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['doc_type', '-min_amount'],
            },
        ),
    ]
