# Generated by Django 5.2.17 on 2026-09-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_seed_default_jv_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrule',
            name='doc_type',
            field=models.CharField(choices=[('journal_entry', 'Journal Entry'), ('invoice', 'Invoice'), ('voucher_receipt', 'Receipt Voucher'), ('voucher_payment', 'Payment Voucher'), ('voucher_settlement', 'Settlement Voucher')], max_length=30, verbose_name='document type'),
        ),
    ]
