# Generated by Django 5.2.17 on 2026-09-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_voucher_fields_and_payment_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrule',
            name='doc_type',
            field=models.CharField(choices=[('journal_entry', 'Journal Entry'), ('invoice', 'Invoice'), ('voucher_receipt', 'Receipt Voucher'), ('voucher_payment', 'Payment Voucher'), ('voucher_settlement', 'Settlement Voucher'), ('iban_change', 'IBAN Change Request')], max_length=30, verbose_name='document type'),
        ),
    ]
