# Generated by Django 5.2.17 on 2026-09-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0007_seed_opening_balance_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrule',
            name='doc_type',
            field=models.CharField(choices=[('journal_entry', 'Journal Entry'), ('invoice', 'Invoice'), ('voucher_receipt', 'Receipt Voucher'), ('voucher_payment', 'Payment Voucher'), ('voucher_settlement', 'Settlement Voucher'), ('iban_change', 'IBAN Change Request'), ('opening_balance', 'Opening Balance'), ('recurring_entry', 'Recurring Entry')], max_length=30, verbose_name='document type'),
        ),
    ]
