# Generated by Django 5.2.17 on 2026-09-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0013_seed_default_asset_addition_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrule',
            name='doc_type',
            field=models.CharField(choices=[('journal_entry', 'Journal Entry'), ('invoice', 'Invoice'), ('voucher_receipt', 'Receipt Voucher'), ('voucher_payment', 'Payment Voucher'), ('voucher_settlement', 'Settlement Voucher'), ('iban_change', 'IBAN Change Request'), ('opening_balance', 'Opening Balance'), ('recurring_entry', 'Recurring Entry'), ('asset_depreciation', 'Asset Depreciation'), ('asset_addition', 'Asset Addition'), ('asset_disposal', 'Asset Disposal')], max_length=30, verbose_name='document type'),
        ),
    ]
