# Generated by Django 5.2.17 on 2026-10-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0017_unique_active_rule_per_tenant_doctype_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrule',
            name='doc_type',
            field=models.CharField(choices=[('journal_entry', 'Journal Entry'), ('invoice', 'Invoice'), ('voucher_receipt', 'Receipt Voucher'), ('voucher_payment', 'Payment Voucher'), ('voucher_settlement', 'Settlement Voucher'), ('iban_change', 'IBAN Change Request'), ('opening_balance', 'Opening Balance'), ('recurring_entry', 'Recurring Entry'), ('asset_depreciation', 'Asset Depreciation'), ('asset_addition', 'Asset Addition'), ('asset_disposal', 'Asset Disposal'), ('stock_receipt', 'Stock Receipt'), ('stock_issue', 'Stock Issue'), ('stock_transfer', 'Stock Transfer'), ('stock_count', 'Stock Count')], max_length=30, verbose_name='document type'),
        ),
    ]
