# Generated by Django 5.2.17 on 2026-09-23 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0015_backfill_journal_line_currency_and_rate'),
        ('organization', '0003_legalentity_tax_period_type'),
        ('parties', '0001_initial'),
        ('sales', '0018_backfill_invoice_balance_fc'),
        ('tenants', '0010_tenant_storage_used_bytes'),
        ('treasury', '0004_cashbox_max_balance_custody_limit_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('voucher_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('settlement', 'Settlement')], max_length=10, verbose_name='voucher type')),
                ('settlement_kind', models.CharField(blank=True, choices=[('internal_transfer', 'Internal transfer')], max_length=20, null=True, verbose_name='settlement kind')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('date', models.DateField(verbose_name='date')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1, max_digits=18, verbose_name='exchange rate')),
                ('exchange_rate_overridden', models.BooleanField(default=False, verbose_name='exchange rate overridden')),
                ('treasury_kind', models.CharField(choices=[('bank', 'Bank'), ('cash_box', 'Cash box'), ('custody', 'Custody')], max_length=10, verbose_name='treasury kind')),
                ('counter_treasury_kind', models.CharField(blank=True, choices=[('bank', 'Bank'), ('cash_box', 'Cash box'), ('custody', 'Custody')], max_length=10, null=True, verbose_name='counter treasury kind')),
                ('counter_amount_fc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='counter amount')),
                ('party_role', models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('employee', 'Employee'), ('affiliate', 'Affiliate')], max_length=10, null=True, verbose_name='party role')),
                ('payee_name', models.CharField(blank=True, max_length=255, verbose_name='payee name')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=15, verbose_name='payment method')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('total_fc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('total_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total (base)')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='treasury.bank')),
                ('cash_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='treasury.cashbox')),
                ('counter_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counter_vouchers', to='treasury.bank')),
                ('counter_cash_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counter_vouchers', to='treasury.cashbox')),
                ('counter_custody', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counter_vouchers', to='treasury.custody')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('custody', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='treasury.custody')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher', to='accounting.journalentry')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='organization.legalentity')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='parties.party')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='vouchers.voucher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField(verbose_name='line number')),
                ('line_type', models.CharField(choices=[('invoice', 'Invoice settlement'), ('on_account', 'On account'), ('account', 'Direct account')], max_length=10, verbose_name='line type')),
                ('allocated_invoice_fc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='allocated (invoice currency)')),
                ('amount_includes_tax', models.BooleanField(default=False, verbose_name='amount includes tax')),
                ('tax_amount_fc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='tax amount')),
                ('ext_supplier_name', models.CharField(blank=True, max_length=255, verbose_name='supplier name')),
                ('ext_supplier_tax_number', models.CharField(blank=True, max_length=50, verbose_name='supplier tax number')),
                ('ext_invoice_ref', models.CharField(blank=True, max_length=100, verbose_name='supplier invoice ref')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('amount_fc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('amount_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='amount (base)')),
                ('tax_amount_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='tax amount (base)')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='accounting.account')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='organization.costcenter')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='sales.invoice')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='accounting.taxcode')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='VoucherAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_invoice_fc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='allocated (invoice currency)')),
                ('base_at_invoice_rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='base at invoice rate')),
                ('base_settled', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='base settled')),
                ('fx_difference_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='FX difference (base)')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='reversed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('voucher_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='vouchers.voucherline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('tenant', 'number'), name='unique_voucher_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bank__isnull', False), ('cash_box__isnull', True), ('custody__isnull', True)), models.Q(('bank__isnull', True), ('cash_box__isnull', False), ('custody__isnull', True)), models.Q(('bank__isnull', True), ('cash_box__isnull', True), ('custody__isnull', False)), _connector='OR'), name='voucher_exactly_one_treasury_account'),
        ),
    ]
