# Generated by Django 5.2.17 on 2026-09-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_source_statement_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('settlement', 'Settlement Voucher')], max_length=10, verbose_name='voucher type'),
        ),
    ]
