# Generated by Django 5.2.17 on 2026-09-30 20:53
# Sprint 6.6.3 (item 2): AddIndex -> AddIndexConcurrently + atomic =
# False — see apps/accounting/migrations/0034's own comment.

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('accounting', '0034_journalentry_accounting_je_entity_date_idx_and_more'),
        ('organization', '0005_legalentity_opening_approved_at'),
        ('parties', '0005_backfill_credit_limit_from_role_details'),
        ('tenants', '0015_tenant_require_2fa_for_roles'),
        ('treasury', '0008_move_untouched_treasury_to_branch'),
        ('vouchers', '0004_legacy_duplicate_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='voucher',
            index=models.Index(fields=['tenant', 'legal_entity', 'date'], name='vouchers_entity_date_idx'),
        ),
        AddIndexConcurrently(
            model_name='voucher',
            index=models.Index(fields=['tenant', 'status'], name='vouchers_status_idx'),
        ),
    ]
