# Generated by Django 5.2.17 on 2026-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_approvals_email',
            field=models.BooleanField(default=True, verbose_name='notify approvals by email'),
        ),
    ]
