# Generated by Django 5.2.17 on 2026-10-10 13:06
#
# Sprint 7.2.9 (§8.9, رule 30): هذه هجرة إنشاء جدول جديد فقط
# (accounts_passwordresettoken) — لا تُحدِّث أي صفّ قائم في أي جدول
# آخر، ولا تمسّ أي قيد مرحَّل أو أي بيانات محاسبية. Explicit per the
# owner's own instruction (أ-١): declare this in the migration file
# itself, not only in the commit message.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password_user_totp_confirmed_and_more'),
        ('tenants', '0016_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
