# Generated by Django 5.2.17 on 2026-09-18 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('center_type', models.CharField(choices=[('department', 'Department'), ('vehicle', 'Vehicle'), ('warehouse', 'Warehouse'), ('employee', 'Employee'), ('project', 'Project'), ('general', 'General')], max_length=20, verbose_name='type')),
                ('linked_object_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.costcenter')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_cost_center_code_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('entity_type', models.CharField(choices=[('holding', 'Holding'), ('company', 'Company'), ('branch', 'Branch')], max_length=20, verbose_name='type')),
                ('country_code', models.CharField(default='SA', max_length=2, verbose_name='country code')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='tax number')),
                ('base_currency', models.CharField(default='SAR', max_length=3, verbose_name='base currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'legal entities',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_legal_entity_code_per_tenant')],
            },
        ),
    ]
