# Generated by Django 5.2.17 on 2026-09-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_backfill_default_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='tax_period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=10, verbose_name='tax period type'),
        ),
    ]
