# Generated by Django 5.2.17 on 2026-09-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_legalentity_tax_period_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='building number'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='commercial_registration',
            field=models.CharField(blank=True, max_length=20, verbose_name='commercial registration'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='district',
            field=models.CharField(blank=True, max_length=255, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='short_address',
            field=models.CharField(blank=True, max_length=10, verbose_name='short address'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='street'),
        ),
    ]
