# Generated by Django 5.2.17 on 2026-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_legalentity_building_number_legalentity_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='opening_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
