# Generated by Django 5.2.17 on 2026-09-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.BooleanField(default=True, verbose_name='organization structure')),
                ('cost_centers', models.BooleanField(default=True, verbose_name='cost centers')),
                ('inventory', models.BooleanField(default=False, verbose_name='inventory')),
                ('purchasing', models.BooleanField(default=False, verbose_name='purchasing')),
                ('hr', models.BooleanField(default=False, verbose_name='HR')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'tenant features',
                'verbose_name_plural': 'tenant features',
            },
        ),
    ]
