# Generated by Django 5.2.17 on 2026-09-18 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
        ('tenants', '0003_backfill_tenant_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='platform.plan'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='trial', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='trial ends at'),
        ),
    ]
