# Generated by Django 5.2.17 on 2026-09-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_plan_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeatures',
            name='assets',
            field=models.BooleanField(default=False, verbose_name='fixed assets'),
        ),
        migrations.AddField(
            model_name='tenantfeatures',
            name='treasury',
            field=models.BooleanField(default=False, verbose_name='treasury'),
        ),
    ]
