# Generated by Django 5.2.17 on 2026-09-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_backfill_treasury_assets_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('service', 'Service'), ('trading', 'Trading'), ('manufacturing', 'Manufacturing'), ('holding', 'Holding')], default='service', max_length=20, verbose_name='business type'),
        ),
    ]
