# Generated by Django 5.2.17 on 2026-09-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0, verbose_name='storage used (bytes)'),
        ),
    ]
