# Generated by Django 5.2.17 on 2026-09-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_storage_used_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='past_due_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='past due since'),
        ),
    ]
