# Generated by Django 5.2.17 on 2026-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_past_due_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='opening_balances_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
