# Generated by Django 5.2.17 on 2026-09-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_opening_balances_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantfeatures',
            name='cost_center_required',
            field=models.BooleanField(default=False, verbose_name='cost center required'),
        ),
        migrations.AddField(
            model_name='tenantfeatures',
            name='credit_limit_mode',
            field=models.CharField(choices=[('warn', 'Warn'), ('block', 'Block')], default='warn', max_length=10, verbose_name='credit limit mode'),
        ),
    ]
