# Generated by Django 5.2.17 on 2026-09-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_default_legal_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='require_2fa_for_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
