# Generated by Django 5.2.17 on 2026-09-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoice_legal_entity_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
