# Generated by Django 5.2.17 on 2026-09-19 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('sales', '0005_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='parties.party'),
        ),
    ]
