# Generated by Django 5.2.17 on 2026-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_backfill_default_entities'),
        ('parties', '0001_initial'),
        ('sales', '0009_invoice_party_not_null'),
        ('tenants', '0008_backfill_treasury_assets_features'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_number_per_tenant',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'legal_entity', 'number'), name='unique_invoice_number_per_tenant_and_entity'),
        ),
    ]
