# Generated by Django 5.2.17 on 2026-09-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_taxcode_taxperiod'),
        ('sales', '0013_invoice_created_by_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.taxcode'),
        ),
    ]
