# Generated by Django 5.2.17 on 2026-09-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_invoiceline_tax_code_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance_fc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_fc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='paid'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid')], default='unpaid', max_length=10, verbose_name='payment status'),
        ),
    ]
