# Generated by Django 5.2.17 on 2026-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_backfill_invoice_balance_fc'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivered at'),
        ),
    ]
