# Generated by Django 5.2.17 on 2026-09-23 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_legalentity_building_number_legalentity_city_and_more'),
        ('parties', '0001_initial'),
        ('sales', '0019_invoice_delivered_at'),
        ('tenants', '0010_tenant_storage_used_bytes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_number_per_tenant',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('tenant', 'number'), name='unique_invoice_number_per_tenant'),
        ),
    ]
