# Generated by Django 5.2.17 on 2026-09-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_remove_invoice_unique_invoice_number_per_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_post_delivery_void',
            field=models.BooleanField(default=False, verbose_name='voided after delivery'),
        ),
    ]
