# Generated by Django 5.2.17 on 2026-09-30 20:53
# Sprint 6.6.3 (item 2): AddIndex -> AddIndexConcurrently + atomic =
# False — see apps/accounting/migrations/0034's own comment.

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('organization', '0005_legalentity_opening_approved_at'),
        ('parties', '0005_backfill_credit_limit_from_role_details'),
        ('sales', '0022_legacy_duplicate_number'),
        ('tenants', '0015_tenant_require_2fa_for_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'legal_entity', 'issue_date'], name='sales_invoice_entity_date_idx'),
        ),
        AddIndexConcurrently(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='sales_invoice_status_idx'),
        ),
    ]
