# Generated by Django 5.2.17 on 2026-10-04 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_fiscalyear_deleted_at_fiscalyear_deleted_by'),
        ('inventory', '0002_unitofmeasure_itemuom_itemcategory_itembarcode_and_more'),
        ('sales', '0025_invoice_deleted_at_invoice_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.itemcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='cogs_account_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_required',
            field=models.BooleanField(default=False, verbose_name='expiry required'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_account_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(default=False, verbose_name='bundle'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='is template'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('service', 'Service')], default='service', max_length=10, verbose_name='item type'),
        ),
        migrations.AddField(
            model_name='product',
            name='karat',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='karat'),
        ),
        migrations.AddField(
            model_name='product',
            name='making_charge_per_gram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='making charge per gram'),
        ),
        migrations.AddField(
            model_name='product',
            name='metal',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='metal'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='sales.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='part number'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_mode',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('weight_rate', 'Weight rate')], default='fixed', max_length=15, verbose_name='pricing mode'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_cost_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='default purchase cost'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='reorder level'),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('serial', 'Serial'), ('batch', 'Batch')], default='', max_length=10, verbose_name='tracking'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='weight (grams)'),
        ),
    ]
