# Generated by Django 5.2.17 on 2026-09-18 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userentityaccess',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='organization.legalentity'),
        ),
        migrations.AddField(
            model_name='userentityaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_role_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='userentityaccess',
            constraint=models.UniqueConstraint(fields=('user', 'legal_entity'), name='unique_user_entity_access'),
        ),
    ]
